INSERT INTO foodcategory (category) VALUES ('Vegetation');
INSERT INTO foodcategory (category) VALUES ('Fruit');
INSERT INTO foodcategory (category) VALUES ('Meat');
INSERT INTO foodcategory (category) VALUES ('Fish');
INSERT INTO foodcategory (category) VALUES ('Plankton');
INSERT INTO vendor (name) VALUES ('Vick''s Veggies');
INSERT INTO vendor (name) VALUES ('Mel''s Meats');
INSERT INTO vendor (name) VALUES ('Freddy''s Fruits');
INSERT INTO vendor (name) VALUES ('Sally''s Seafood');
INSERT INTO enclosurecondition (condition) VALUES ('Clean');
INSERT INTO enclosurecondition (condition) VALUES ('Untidy');
INSERT INTO enclosurecondition (condition) VALUES ('Dirty');
INSERT INTO food (name, foodcategory_id, vendor_id) VALUES ('bananas', 2, 3);
INSERT INTO food (name, foodcategory_id, vendor_id) VALUES ('salmon', 4, 4);
INSERT INTO food (name, foodcategory_id, vendor_id) VALUES ('leaves', 1, 1);
INSERT INTO food (name, foodcategory_id, vendor_id) VALUES ('red meat', 3, 2);
INSERT INTO food (name, foodcategory_id, vendor_id) VALUES ('plankton', 5, 4);
INSERT INTO animal (infoLink, name, sciname, food_id) VALUES ('https://en.wikipedia.org/wiki/Grizzly_bear', 'Grizzly Bear', 'Ursus arctos horribilis', 2);
INSERT INTO animal (infoLink, name, sciname, food_id) VALUES ('https://en.wikipedia.org/wiki/Chimpanzee', 'Chimpanzee', 'Pan', 1);
INSERT INTO animal (infoLink, name, sciname, food_id) VALUES ('https://en.wikipedia.org/wiki/Chimpanzee', 'Bengal tiger', 'Panthera tigris tigris', 4);
INSERT INTO animal (infoLink, name, sciname, food_id) VALUES ('https://en.wikipedia.org/wiki/Shrimp', 'Caridean shrimp', 'Caridea', 5);