INSERT INTO foodcategory (category) VALUES ('Vegetation');
INSERT INTO foodcategory (category) VALUES ('Fruit');
INSERT INTO foodcategory (category) VALUES ('Meat');
INSERT INTO foodcategory (category) VALUES ('Fish');
INSERT INTO foodcategory (category) VALUES ('Plankton');
INSERT INTO foodcategory (category) VALUES ('Algae');
INSERT INTO enclosurecondition (condition) VALUES ('Clean');
INSERT INTO enclosurecondition (condition) VALUES ('Untidy');
INSERT INTO enclosurecondition (condition) VALUES ('Dirty');